version: "3.9"

services:
  db:
    build:
      context: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: benchbase
    command: >
      postgres 
        -c max_connections=450
        -c max_pred_locks_per_transaction=500 
        -c shared_preload_libraries='pg_stat_statements'
    ports:
     - "5432:5432"
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 16GiB

volumes:
  db-data:
